---
title: "Project 2"
author: "Sang Bo Yoon"
date: "2025-11-11"
output: word_document
---

```{r setup, warning = FALSE, message = FALSE, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(tidyverse)
```

```{r}
# data cleaning

clean_data <- function(file_path){
  data <- read_csv(file_path) #import dataset
  
  names(data)[c(2, 4, 6)] <- c("max_CO", "mean_PM2.5", "max_O3") # rename variables
  
  data <- data %>%
    select(Date, max_CO,
           mean_PM2.5, max_O3) %>% # leave out unit columns
    mutate(Date =
             as.Date(Date,
                     format = "%m/%d/%Y")) %>% # convert character string to dates
    group_by(Date) %>%
    mutate( # average multiple measurements
      max_CO = mean(max_CO, na.rm = TRUE),
      mean_PM2.5 = mean(mean_PM2.5, na.rm = TRUE),
      max_O3 = mean(max_O3, na.rm = TRUE)) %>%
    ungroup()

  data <- distinct(data) # remove duplicates
  
  for (col in c(2:4)){ # fix negative values to 0
    data[[col]] <- if_else(data[[col]] < 0,
                           0, data[[col]])
  }
  
  return(data)
}
```

```{r}
# run function on all datasets
AQ_2018 <- clean_data("data/AQ_2018.csv")
AQ_2019 <- clean_data("data/AQ_2019.csv")
AQ_2020 <- clean_data("data/AQ_2020.csv")
```

```{r}
# making plots

combined_AQ <- rbind(AQ_2018, AQ_2019, AQ_2020) #combine datasets

month_year_summary <- combined_AQ %>%
  mutate(month = month(Date, label = TRUE,
                       abbr = TRUE), #add abbreviated month column
         year = format(Date, "%Y")) #add year column

CO_O3_summary <- month_year_summary %>%
  select(Date, month, year, max_CO, max_O3) %>% #only select CO and O3 data
  pivot_longer( #for each date create two entries separate for each pollutant
    cols = c(max_CO, max_O3),
    names_to = "Pollutant",
    values_to = "Concentration"
  )
```

```{r}
CO_O3_graph_data <- CO_O3_summary %>%
  group_by(month, Pollutant) %>% # group by month and pollutant
  summarise(mean =
              mean(Concentration,
                   na.rm = TRUE), # find monthly averages averaged over 3 years
            se = sd(Concentration, na.rm = TRUE) /
              sqrt(sum(!is.na(Concentration)))) %>% # calculate standard error
  mutate(LB = mean - 1.96 * se, #confidence interval lower bound
         UB = mean + 1.96 * se) #upper bound
```

```{r}
# creating the first plot
ggplot(CO_O3_graph_data, aes(x = month, y = mean,
                          color = Pollutant, group = Pollutant)) +
  geom_line(size = 0.5) +
  geom_point(size = 1) +
  geom_errorbar(aes(ymin = LB, ymax = UB), width = 0.2, alpha = 0.7) +
  scale_color_brewer(palette = "Set1",
                     labels = c("CO", "O3")) +
  labs(
    title = "Average Monthly CO & O3 Concentrations (2018-2020)",
    x = "Month",
    y = "Concentration (in ppm)",
    color = "Pollutant"
  ) +
  theme_minimal() +
  theme(
    legend.position = "top",
    plot.title = element_text(face = "bold", hjust = 0.5, size = 13)
  )
```

```{r}
# finding monthly average for last pollutant for each year
PM_summary <- month_year_summary %>%
  group_by(year, month) %>%
  summarise(PM25_mean = mean(mean_PM2.5, na.rm = TRUE))
```

```{r}
#creating second plot
ggplot(PM_summary, aes(x = month, y = PM25_mean,
                       color = year, group = year)) +
  geom_line(size = 0.5) +
  geom_point(size = 1) +
  facet_wrap(~ year, nrow = 3) + # 3 separate rows of plots
  scale_color_brewer(palette = "Set1") +
  labs(
    title = "Average Monthly PM2.5 Concentrations by Year",
    x = "Month",
    y = "Concentration (in ug/m3 LC)",
    color = "Year"
  ) +
  theme_minimal() +
  theme(
    legend.position = "none",
    plot.title = element_text(face = "bold", hjust = 0.5, size = 13)
  )
```
